// routes/detect.js
const express = require("express");
const router  = express.Router();
const Groq    = require("groq-sdk");
const axios   = require("axios");
const cheerio = require("cheerio");
const multer  = require("multer");
const { v4: uuidv4 } = require("uuid");
const db = require("../db");

// ─── PDF Parser ───────────────────────────────────────────────────────────────
// pdf-parse v2.x exports { PDFParse } — use require('pdf-parse') directly
let PDFParse;
try {
  PDFParse = require("pdf-parse").PDFParse;
  console.log("[PDF] PDFParse loaded:", typeof PDFParse);
} catch (e) {
  console.error("[PDF] Failed to load pdf-parse:", e.message);
}

// ─── Groq Client ─────────────────────────────────────────────────────────────
const client = new Groq({ apiKey: process.env.GROQ_API_KEY });

// ─── Multer ───────────────────────────────────────────────────────────────────
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 },
  fileFilter(req, file, cb) {
    const allowedMimes = [
      "text/plain", "text/html", "text/markdown",
      "application/pdf",
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "application/octet-stream",
      "binary/octet-stream",
    ];
    const allowedExt = /\.(txt|md|html|htm|pdf)$/i;
    if (allowedMimes.includes(file.mimetype) || allowedExt.test(file.originalname)) {
      cb(null, true);
    } else {
      cb(new Error(`Unsupported file: ${file.mimetype} / ${file.originalname}`));
    }
  },
});

// ─── System Prompt ────────────────────────────────────────────────────────────
const SYSTEM_PROMPT = `You are an expert AI text detection system. Analyze the provided text and determine if it was written by a human or generated by an AI (like ChatGPT, Claude, Gemini, Llama, etc.).

Respond ONLY with valid JSON in this exact structure (no markdown, no preamble):
{
  "verdict": "AI" | "Human" | "Mixed",
  "ai_probability": <integer 0-100>,
  "confidence": "Low" | "Medium" | "High" | "Very High",
  "summary": "<2-3 sentence explanation of your verdict>",
  "signals": {
    "perplexity":         { "score": <0-100, higher=more predictable/AI-like>, "label": "<brief note>" },
    "burstiness":         { "score": <0-100, higher=more varied/human-like>,   "label": "<brief note>" },
    "vocabulary":         { "score": <0-100, higher=richer/more human-like>,   "label": "<brief note>" },
    "sentence_structure": { "score": <0-100, higher=more formulaic/AI-like>,   "label": "<brief note>" }
  },
  "ai_flags": ["<observation suggesting AI authorship>"],
  "human_flags": ["<observation suggesting human authorship>"],
  "suspicious_phrases": ["<exact short phrase from text typical of AI writing>"],
  "word_count": <integer>,
  "sentence_count": <integer>,
  "avg_sentence_length": <number>
}

Detection criteria:
- AI signals: Predictable transitions (Furthermore, Moreover, In conclusion), structured lists, neutral tone, hedging qualifiers, uniform sentence length, perfect grammar, no personal anecdotes, typical AI words (delve, crucial, notably, comprehensive, pivotal, multifaceted, nuanced, leverage, underscore, paramount).
- Human signals: Slang, contractions, typos, varied sentence length, strong opinions, emotional nuance, storytelling, informal language, personal voice.
- Calibration: 0-15% = clearly human, 15-40% = mostly human/uncertain, 55-100% = AI generated.`;

// ─── Helpers ──────────────────────────────────────────────────────────────────

const https = require("https");

async function extractFromUrl(url) {
  const res = await axios.get(url, {
    timeout: 15000,
    httpsAgent: new https.Agent({ rejectUnauthorized: false }),
    headers: {
      "User-Agent": "Mozilla/5.0 (compatible; AIDetectorBot/1.0)",
      "Accept": "text/html,application/xhtml+xml",
    },
    maxContentLength: 2 * 1024 * 1024,
  });
  const $ = cheerio.load(res.data);
  $("script,style,nav,header,footer,aside,iframe,noscript").remove();
  const text =
    $("article").text() ||
    $("main").text()    ||
    $('[role="main"]').text() ||
    $("body").text()    || "";
  return text.replace(/\s+/g, " ").trim();
}

async function extractFromFile(buffer, mimetype, originalname) {
  const isPDF =
    mimetype === "application/pdf" ||
    originalname.toLowerCase().endsWith(".pdf");

  if (isPDF) {
    if (!PDFParse) {
      throw new Error(
        "PDF parser failed to load. Check server logs. " +
        "You can also copy-paste the PDF text into the text tab as a workaround."
      );
    }
    try {
      console.log(`[PDF] Parsing: ${originalname} (${buffer.length} bytes)`);
      const parser = new PDFParse({ data: buffer });
      const result = await parser.getText();

      // pdf-parse v2.x returns { text, pages, total }
      const raw = (result && typeof result.text === "string")
        ? result.text
        : (result && Array.isArray(result.pages))
          ? result.pages.map(p => p.text || "").join("\n")
          : "";

      const text = raw.replace(/\s+/g, " ").trim();
      console.log(`[PDF] Extracted ${text.length} chars from ${originalname}`);

      if (text.length < 50) {
        throw new Error(
          "No readable text extracted from this PDF. " +
          "It may be a scanned image or contain only graphics. " +
          "Try copy-pasting the text into the text tab instead."
        );
      }
      return text;
    } catch (err) {
      console.error("[PDF] Error:", err.message);
      throw new Error(err.message.startsWith("No readable")
        ? err.message
        : "PDF extraction failed: " + err.message
      );
    }
  }

  return buffer.toString("utf-8");
}

async function callGroqDetection(text) {
  const truncated = text.slice(0, 8000);
  const completion = await client.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      { role: "user",   content: `Analyze this text:\n\n${truncated}` },
    ],
    temperature: 0.1,
    max_tokens: 1024,
    response_format: { type: "json_object" },
  });
  const raw = completion.choices[0]?.message?.content || "{}";
  return JSON.parse(raw.replace(/```json|```/g, "").trim());
}

// ─── Routes ───────────────────────────────────────────────────────────────────

router.post("/text", async (req, res) => {
  try {
    const { text } = req.body;
    if (!text || typeof text !== "string")
      return res.status(400).json({ error: "text field is required" });
    if (text.trim().split(/\s+/).length < 20)
      return res.status(400).json({ error: "Text too short — minimum 20 words required." });

    const result = await callGroqDetection(text.trim());
    const id = uuidv4();
    await db.saveScan({ id, source_type:"text", source_ref:null,
      input_text:text.trim().slice(0,500), word_count:result.word_count,
      verdict:result.verdict, ai_prob:result.ai_probability,
      confidence:result.confidence, summary:result.summary,
      signals:result.signals, ai_flags:result.ai_flags,
      human_flags:result.human_flags, phrases:result.suspicious_phrases,
      ip_address:req.ip });
    res.json({ id, ...result });
  } catch (err) {
    console.error("detect/text:", err.message);
    res.status(500).json({ error: err.message || "Detection failed" });
  }
});

router.post("/url", async (req, res) => {
  try {
    const { url } = req.body;
    if (!url || !/^https?:\/\/.+/.test(url))
      return res.status(400).json({ error: "Valid URL is required" });

    const text = await extractFromUrl(url);
    if (text.split(/\s+/).length < 20)
      return res.status(400).json({ error: "Not enough readable text at that URL." });

    const result = await callGroqDetection(text);
    const id = uuidv4();
    await db.saveScan({ id, source_type:"url", source_ref:url,
      input_text:text.slice(0,500), word_count:result.word_count,
      verdict:result.verdict, ai_prob:result.ai_probability,
      confidence:result.confidence, summary:result.summary,
      signals:result.signals, ai_flags:result.ai_flags,
      human_flags:result.human_flags, phrases:result.suspicious_phrases,
      ip_address:req.ip });
    res.json({ id, url, ...result });
  } catch (err) {
    console.error("detect/url:", err);
    const message = err?.response?.data?.error || err?.message || "Unknown URL detection error";
    res.status(500).json({ error: message });
  }
});

router.post("/file", upload.single("file"), async (req, res) => {
  try {
    if (!req.file)
      return res.status(400).json({ error: "No file uploaded" });

    console.log(`[FILE] ${req.file.originalname} | ${req.file.mimetype} | ${req.file.size}b`);

    const text = await extractFromFile(req.file.buffer, req.file.mimetype, req.file.originalname);
    if (!text || text.trim().split(/\s+/).length < 20)
      return res.status(400).json({ error: "File contains too little readable text (min 20 words)." });

    const result = await callGroqDetection(text.trim());
    const id = uuidv4();
    await db.saveScan({ id, source_type:"file", source_ref:req.file.originalname,
      input_text:text.trim().slice(0,500), word_count:result.word_count,
      verdict:result.verdict, ai_prob:result.ai_probability,
      confidence:result.confidence, summary:result.summary,
      signals:result.signals, ai_flags:result.ai_flags,
      human_flags:result.human_flags, phrases:result.suspicious_phrases,
      ip_address:req.ip });
    res.json({ id, filename:req.file.originalname, ...result });
  } catch (err) {
    console.error("detect/file:", err.message);
    res.status(500).json({ error: err.message || "Detection failed" });
  }
});

module.exports = router;