// routes/detect.js — Core detection endpoint
const express = require("express");
const router  = express.Router();
const Groq = require("groq-sdk");
const axios   = require("axios");
const cheerio = require("cheerio");
const multer  = require("multer");
const { v4: uuidv4 } = require("uuid");
const db = require("../db");
const pdf = require("pdf-parse");

const client = new Groq({ apiKey: process.env.GROQ_API_KEY });

// Multer: memory storage, 5MB limit, text files only
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 },
  fileFilter(req, file, cb) {
    const allowed = ["text/plain", "text/html", "text/markdown", "application/pdf",
                     "application/msword",
                     "application/vnd.openxmlformats-officedocument.wordprocessingml.document"];
    if (allowed.includes(file.mimetype) || file.originalname.match(/\.(txt|md|html|htm)$/i)) {
      cb(null, true);
    } else {
      cb(new Error("Unsupported file type. Allowed: .txt, .md, .html, .pdf"));
    }
  },
});

// ─── System Prompt ────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are an expert AI text detection system. Analyze the provided text and determine if it was written by a human or generated by an AI (like ChatGPT, Claude, Gemini, Llama, etc.).

Respond ONLY with valid JSON in this exact structure (no markdown, no preamble):
{
  "verdict": "AI" | "Human" | "Mixed",
  "ai_probability": <integer 0-100>,
  "confidence": "Low" | "Medium" | "High" | "Very High",
  "summary": "<2-3 sentence explanation of your verdict>",
  "signals": {
    "perplexity":         { "score": <0-100, higher=more predictable/AI-like>, "label": "<brief note>" },
    "burstiness":         { "score": <0-100, higher=more varied/human-like>,   "label": "<brief note>" },
    "vocabulary":         { "score": <0-100, higher=richer/more human-like>,   "label": "<brief note>" },
    "sentence_structure": { "score": <0-100, higher=more formulaic/AI-like>,   "label": "<brief note>" }
  },
  "ai_flags": ["<observation suggesting AI authorship>"],
  "human_flags": ["<observation suggesting human authorship>"],
  "suspicious_phrases": ["<exact short phrase from text typical of AI writing>"],
  "word_count": <integer>,
  "sentence_count": <integer>,
  "avg_sentence_length": <number>
}

### Detection Guidelines
1. **AI Characteristics**: Predictable transitions (Furthermore, Moreover), structured lists, neutral tone, hedging/qualifiers, uniform length, "clean" grammar, lack of personal subtext.
2. **Human Characteristics**: Slang, informal contractions, typos, varied sentence length, emotional nuance, strong opinions, storytelling (Reddit/forum style), conversational quirks.

### Few-Shot Examples

#### Example 1: AI-GENERATED (Probability: 85-100%)
"I wanted to share a piece of advice... If you spot a girl you're interested in, don’t overthink it—just approach her! 1. Set a Time Limit... 2. Keep it Casual... 3. Embrace Rejection... 4. Be Authentic... 5. Practice Makes Perfect... Ultimately, remember that every girl has her own preferences..."
*Note: Very structured, list-based, instructional, and neutral.*

#### Example 2: HUMAN-WRITTEN (Probability: 0-10%)
"What's not to like about this movie? Every year you know that you're going to get one or two yule tide movies during Christmas time and most of them are going to be terrible. This movie is definitely a fresh new idea that was pulled off pretty well. A very funny take on a rich young guy... Only if."
*Note: Opinionated, conversational, uses specific idioms."*

#### Example 3: HUMAN-WRITTEN (Probability: 0-15%)
"This happened yesterday and also english is not my first language so apologize if there are any grammatical error. Me being horny af because of exams... fuck better take care of this... I pulled my pants waistband down... I barge right in... God I'm so fucked."
*Note: Heavy slang, informal, strong emotional context, storyteller vibe.*

### Calibration Rules
- **NATURAL HUMAN (0-5%)**: Use this for natural, informal, or personal storytelling. If it sounds like a real person talking or typing, it MUST be in this range.
- **FORMAL HUMAN (5-20%)**: Use this for formal, academic, or professional human writing (e.g., a news article or research paper).
- **MIXED/UNCERTAIN (20-50%)**: Use this only if there are conflicting signals.
- **AI-GENERATED (55-100%)**: Use this for clear AI authorship.

**IMPORTANT**: A probability of 20% or less MUST result in a 'Human' verdict. 
**DO NOT default to 20% for human text.** If it is clearly human, be bold and give it a **0-5%** score. Only use 10-20% if the human writing is exceptionally "perfect" or robotic.`;

// ─── Helpers ─────────────────────────────────────────────────────────────────

async function extractFromUrl(url) {
  const res = await axios.get(url, {
    timeout: 12000,
    headers: {
      "User-Agent": "Mozilla/5.0 (compatible; AIDetectorBot/1.0)",
      "Accept": "text/html,application/xhtml+xml",
    },
    maxContentLength: 2 * 1024 * 1024,
  });
  const $ = cheerio.load(res.data);
  $("script, style, nav, header, footer, aside, iframe, noscript, .ad, #ad").remove();
  const article = $("article").text() || $("main").text() || $('[role="main"]').text() || $("body").text();
  return article.replace(/\s+/g, " ").trim();
}

async function extractFromFile(buffer, mimetype, originalname) {
  if (mimetype === "application/pdf" || originalname.toLowerCase().endsWith(".pdf")) {
    try {
      console.log(`[EXTRACT] PDF Buffer size: ${buffer.length}, Type: ${typeof buffer}, isBuffer: ${Buffer.isBuffer(buffer)}`);
      console.log(`[EXTRACT] Magic bytes: ${buffer.slice(0, 4).toString()}`); 
      const data = await pdf(buffer);
      console.log(`[EXTRACT] Extracted ${data.text?.length || 0} characters from PDF`);
      return data.text;
    } catch (err) {
      console.error("PDF Extraction Error Trace:", err);
      throw new Error(`Failed to extract text from PDF: ${err.message}`);
    }
  }
  // For text-based files just decode the buffer
  return buffer.toString("utf-8");
}

async function callGroqDetection(text) {
  const truncated = text.slice(0, 8000); 
  const completion = await client.chat.completions.create({
    model: "llama-3.3-70b-versatile",
    messages: [
      { role: "system", content: SYSTEM_PROMPT },
      { role: "user",   content: `Analyze this text:\n\n${truncated}` }
    ],
    temperature: 0.1,
    max_tokens: 1024,
    response_format: { type: "json_object" }
  });

  const raw = completion.choices[0]?.message?.content || "";
  return JSON.parse(raw);
}

// ─── Routes ──────────────────────────────────────────────────────────────────

// POST /api/detect/text
router.post("/text", async (req, res) => {
  try {
    const { text } = req.body;
    if (!text || typeof text !== "string") {
      return res.status(400).json({ error: "text field is required" });
    }
    if (text.trim().split(/\s+/).length < 20) {
      return res.status(400).json({ error: "Text too short. Minimum 20 words required." });
    }

    const result = await callGroqDetection(text.trim());
    const id = uuidv4();

    await db.saveScan({
      id,
      source_type: "text",
      source_ref:  null,
      input_text:  text.trim().slice(0, 500),
      word_count:  result.word_count,
      verdict:     result.verdict,
      ai_prob:     result.ai_probability,
      confidence:  result.confidence,
      summary:     result.summary,
      signals:     result.signals,
      ai_flags:    result.ai_flags,
      human_flags: result.human_flags,
      phrases:     result.suspicious_phrases,
      ip_address:  req.ip,
    });

    res.json({ id, ...result });
  } catch (err) {
    console.error("detect/text error:", err);
    res.status(500).json({ error: err.message || "Detection failed" });
  }
});

// POST /api/detect/url
router.post("/url", async (req, res) => {
  try {
    const { url } = req.body;
    if (!url || !/^https?:\/\/.+/.test(url)) {
      return res.status(400).json({ error: "Valid URL is required" });
    }

    const text = await extractFromUrl(url);
    if (text.split(/\s+/).length < 20) {
      return res.status(400).json({ error: "Not enough readable text found at that URL." });
    }

    const result = await callGroqDetection(text);
    const id = uuidv4();

    await db.saveScan({
      id,
      source_type: "url",
      source_ref:  url,
      input_text:  text.slice(0, 500),
      word_count:  result.word_count,
      verdict:     result.verdict,
      ai_prob:     result.ai_probability,
      confidence:  result.confidence,
      summary:     result.summary,
      signals:     result.signals,
      ai_flags:    result.ai_flags,
      human_flags: result.human_flags,
      phrases:     result.suspicious_phrases,
      ip_address:  req.ip,
    });

    res.json({ id, url, ...result });
  } catch (err) {
    console.error("detect/url error:", err);
    const msg = err.code === "ECONNABORTED" ? "URL request timed out" : err.message;
    res.status(500).json({ error: msg || "Detection failed" });
  }
});

// POST /api/detect/file
router.post("/file", upload.single("file"), async (req, res) => {
  try {
    console.log(`[FILE UPLOAD] Received: ${req.file?.originalname} (${req.file?.size} bytes)`);
    if (!req.file) return res.status(400).json({ error: "No file uploaded" });

    const text = await extractFromFile(req.file.buffer, req.file.mimetype, req.file.originalname);
    if (!text || text.trim().split(/\s+/).length < 20) {
      return res.status(400).json({ error: "File contains too little readable text." });
    }

    const result = await callGroqDetection(text.trim());
    const id = uuidv4();

    await db.saveScan({
      id,
      source_type: "file",
      source_ref:  req.file.originalname,
      input_text:  text.trim().slice(0, 500),
      word_count:  result.word_count,
      verdict:     result.verdict,
      ai_prob:     result.ai_probability,
      confidence:  result.confidence,
      summary:     result.summary,
      signals:     result.signals,
      ai_flags:    result.ai_flags,
      human_flags: result.human_flags,
      phrases:     result.suspicious_phrases,
      ip_address:  req.ip,
    });

    res.json({ id, filename: req.file.originalname, ...result });
  } catch (err) {
    console.error("detect/file error:", err);
    res.status(500).json({ error: err.message || "Detection failed" });
  }
});

module.exports = router;
